---
# defaults file for openshift

# OpenShift version
openshift_version: "4.18"
# OpenShift release channel
openshift_release_channel: "stable"

# OpenShift Cluster Info
# Cluster name
cluster_name: "example-cluster"
# Base domain
base_domain: "amd.com"
# API VIP DNS entry
api_dns_vip: "api.{{ cluster_name }}.{{ base_domain }}"
# Ingress VIP DNS entry
ingress_dns_vip: "test.apps.{{ cluster_name }}.{{ base_domain }}"
# API VIP address
api_vip: "10.216.189.199"
# Ingress VIP address
ingress_vip: "10.216.189.199"
# Number of worker nodes
worker_nodes_count: 2
# Number of master nodes  
master_nodes_count: 3
# OpenShift Pull Secret
openshift_pull: ""
# OpenShift SSH Key
openshift_ssh_key: ""

# OpenShift Install Info
# OpenShift install directory
openshift_install_dir: "/tmp/openshift"

# Network Info
gateway_ip: ""
nameserver_ip: 
  - ""
rendezvous_ip: "" # Ip address of the rendezvous node, usually first node in the list
# HTTP Server Info localhost
http_server_ip: "{{ ansible_host }}"
http_server_port: "80"

# Baremetal Info
# Master Nodes
baremetal_master_nodes:
  - name: "master-0"
    nics:
      - name: "ens3"
        ip: "10.216.189.199"
        mac: "00:00:00:00:00:01"
        dhcp: false
    install_disk: "/dev/sda"
  - name: "master-1"
    nics:
      - name: "ens3"
        ip: "10.216.189.199"
        mac: "00:00:00:00:00:02"
        dhcp: false
    install_disk: "/dev/sda"
  - name: "master-2"
    ip: "10.216.189.199"
    mac: "00:00:00:00:00:03"
    install_disk: "/dev/sda"
# Worker Nodes
baremetal_worker_nodes:
  - name: "worker-0"
    nics:
      - name: "ens3"
        ip: "10.216.189.199"
        mac: "00:00:00:00:00:04"
        dhcp: false
    install_disk: "/dev/sda"
  - name: "worker-1"
    nics:
      - name: "ens3"
        ip: "10.216.189.199"
        mac: "00:00:00:00:00:05"
        dhcp: false
    install_disk: "/dev/sda"

# Common BMC Info
redfish_user: "admin"
redfish_password: "amd1234!"
redfish_port: "443"
redfish_protocol: "https"
redfish_bmc_type: "redfish"
# Redfish BMC Info
redfish_bmc:
  - name: "master-0"
    redfish_ip: "xcc-7d9a-J1050MC1.amd.com"
    validate_certs: false
  - name: "master-1"
    redfish_ip: "xcc-7d9a-J1050MBL.amd.com"
    validate_certs: false
  - name: "master-2"
    redfish_ip: "xcc-7d9a-J1050MBB.amd.com"
    validate_certs: false
  - name: "worker-0"
    redfish_ip: "xcc-7d9a-J1050MBA.amd.com"
    validate_certs: false
  - name: "worker-1"
    redfish_ip: "xcc-7d76-JZ001CLD.amd.com"
    validate_certs: false