---
- name: Gather vendor info
  ansible.builtin.uri: 
    url: "https://{{ item.redfish_ip }}:{{ redfish_port }}/redfish/v1"
    method: GET
    user: "{{ redfish_user }}"
    password: "{{ redfish_password }}"
    validate_certs: "{{ item.validate_certs }}"
    return_content: yes
    status_code: 200
  register: redfish_info
  loop: "{{ redfish_bmc }}"
  loop_control:
    label: "{{ item.name }}"
  when: redfish_bmc is defined
  ignore_errors: true
  tags: openshift_baremetal_hosts

- name: Display manufacturer info
  debug:
    msg: "Manufacturer: {{ item.item.name }} is a {{ item.json.Vendor }} server"
  loop: "{{ redfish_info.results }}"
  tags: openshift_baremetal_hosts

- name: Set vendor facts for each server
  set_fact:
    enhanced_servers: >-
      {{ 
        redfish_bmc | map('combine', {
          'vendor': item.item.vendor | default(
            (item.status is defined and item.status == 200) | ternary(
              (
                'lenovo' if 'Lenovo' in (item.json.Vendor | default('')) else (
                'dell' if 'Dell' in (item.json.Manufacturer | default('')) or 'Dell' in (item.json.VendorName | default('')) else (
                'hpe' if 'HPE' in (item.json.Manufacturer | default('')) or 'Hewlett Packard Enterprise' in (item.json.Manufacturer | default('')) else (
                'openbmc' if 'OpenBMC' in (item.json.Manufacturer | default('')) or 'OpenBMC Project' in (item.json.Manufacturer | default('')) else
                'unknown'
                )))
              ),
              item.item.vendor | default('unknown')
            )
          )
        }) | list
      }}
  loop: "{{ redfish_info.results if redfish_info.results is defined else [] }}"
  loop_control:
    label: "{{ item.item.name if item.item is defined else 'unknown' }}"
  when: redfish_info.results is defined
  run_once: true
  tags: openshift_baremetal_hosts

# If no vendors were detected, keep original list
- name: Use original server list if no vendor detection was done
  set_fact:
    enhanced_servers: "{{ redfish_servers }}"
  when: redfish_info.results is not defined
  tags: openshift_baremetal_hosts

- name: Display enhanced server list
  debug:
    msg: "Enhanced server list: {{ enhanced_servers }}"
  tags: openshift_baremetal_hosts

- name: Run Lenovo Specific Tasks
  include_tasks: lenovo.yml
  when: server.vendor == "lenovo"
  loop: "{{ enhanced_servers }}"
  loop_control:
    loop_var: "server"
  tags: openshift_baremetal_hosts

