---
# tasks file for openshift

- name: Setup Pre-requisites
  include_tasks: os_setup.yml
  tags:
    - openshift
    - openshift_prerequisites
- name: Install OpenShift binaries
  include_tasks: install_openshift.yml
  tags:
    - openshift
    - openshift_install

- name: Create OpenShift Agent Image
  include_tasks: openshift_agent_image.yml
  tags:
    - openshift
    - openshift_agent_image

- name: Setup Web Server
  include_tasks: web_server.yml
  tags:
    - openshift
    - openshift_web_server

- name: Setup Baremetal Hosts
  include_tasks: baremetal_hosts.yml
  tags:
    - openshift_baremetal_hosts

    