---
- name: Create the install directory
  ansible.builtin.file:
    name: "{{ openshift_agent_install_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy template files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ openshift_agent_install_dir }}/{{ item | basename }}"
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - "install-config.yaml.j2"
    - "agent-config.yaml.j2"
  register: template_files

- name: Run openshift-install create agent
  ansible.builtin.command:
    cmd: >
      openshift-install create agent
      --dir={{ openshift_agent_install_dir }}
      --log-level=debug
  register: create_agent_output
  failed_when : create_agent_output.rc != 0

- name: Check if the agent ISO was created
  ansible.builtin.stat:
    path: "{{ openshift_agent_install_dir }}/agent.x86_64.iso"
  register: agent_iso
  failed_when: agent_iso.stat.exists == false

