---
- name: Get OS Info
  ansible.builtin.debug:
    msg: "OS Name: {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Install required packages
  block:
    - name: Update OS repositories
      ansible.builtin.dnf:
        update_cache: yes
        cache_valid_time: 3600
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: Install required packages for RHEL/CentOS
      ansible.builtin.dnf:
        name:
          - git
          - wget
          - curl
          - vim
          - bind-utils
        state: present
  when: ansible_os_family == "RedHat"

- name: Install required packages for Ubuntu
  block:
    - name: Update OS repositories
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
    - name: Install required packages for Ubuntu
      ansible.builtin.apt:
        name:
          - git
          - wget
          - curl
          - vim
          - net-tools
          - dnsutils
        state: present
  when: ansible_os_family == "Debian"

# TODO: Install required packages for SLES